### ISSUE TITLE
detects

### ISSUE THREAD

**Issue by Lawxsz** [6nz/python-anti-debugger#6]
Hi, a funny thing but I noticed it today.

When using os.exit(1) you add detections, when using sys.exit() they go down, that is to say to me I change 1 detection and mark as trojan in the new GUI section.

**Comment by 6nz** [comment]
Hi thanks for telling me
Im using os.exit(1) bc it can stop multiple running threads at the same time sys.exit wont stop looped threads

**Comment by 6nz** [comment]
![image](https://user-images.githubusercontent.com/74118308/222827567-73271f77-7c4a-4f74-b838-1576757ac943.png)

**Comment by 6nz** [comment]
os._exit is faster and better

**Comment by Lawxsz** [comment]
> os._exit is faster and better

I know it is better and faster, but it still leaves more detections.

**Comment by 6nz** [comment]
what detections exactly

**Comment by 6nz** [comment]
obfuscate the code, encrypt the modules and modify pyinstaller's source code to reduce the detections
or use other compilers like Nuitka

**Comment by 6nz** [comment]
if os._exit() is flagged then the whole os module should get flagged everytime

**Comment by 6nz** [comment]
![image](https://user-images.githubusercontent.com/74118308/222829790-c73e57c9-cd56-4370-8bb4-5b173b37bdfe.png)

**Comment by 6nz** [comment]
old pic of my virus that is using this anti debug system and no detections

**Comment by 6nz** [comment]
i just obfuscated the code, modules and modified pyinstaller's src

**Comment by Lawxsz** [comment]
> i just obfuscated the code, modules and modified pyinstaller's src

good bro nice, do you use pyarmor, aes, fernet or?

**Comment by 6nz** [comment]
pyarmor, aes, base64
